---
- hosts: localhost
  become: yes
  tasks:
  - name: installing Apache2
    apt:
      name: apache2
      update_cache: yes
      state: present 
  - name: Starting Apache2    
    service:
      name: apache2
      state: started 
      enabled: yes
  